# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170114_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
