# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170115_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='published_date',
        ),
    ]
